const Menu = [
  {
    id: 1,
    image: "https://media.istockphoto.com/id/636761588/photo/used-brushes-on-an-artists-palette-of-colorful-oil-paint.jpg?s=1024x1024&w=is&k=20&c=fpHRSW_YAwiPWpbqHlqJvaAId_8e9BmzGBlgKr_1Zi4=",
    name: "Abstract Canvas Art",
    category: "abstract art",
    type: "abstract",
    price: "500₹",
    description: "A beautiful abstract canvas art piece that adds color and style to your space.",
  },
  {
    id: 2,
    image: "https://media.istockphoto.com/id/1183183791/photo/talented-female-artist-works-on-abstract-oil-painting-using-paint-brush-she-creates-modern.jpg?s=612x612&w=0&k=20&c=QrR6QQxioyM6zT5qPpKxr9KFz2VRrhVO3rXJ8fIfswY=",
    name: "Landscape Painting",
    category: "scenic",
    type: "landscape",
    price: "800₹",
    description: "A stunning landscape painting that captures the beauty of nature.",
  },
  {
    id: 3,
    image: "https://media.istockphoto.com/id/1134512518/photo/abstract-hand-painted-art-background-on-canvas.jpg?s=612x612&w=0&k=20&c=9q1y7CGMBGpoVzVKCIvRqQrE9FZu3F4VGfjIcUHgpvY=",
    name: "Modern Abstract Art",
    category: "abstract art",
    type: "abstract",
    price: "600₹",
    description: "A contemporary abstract art piece that sparks creativity and imagination.",
  },
  {
    id: 4,
    image: "https://media.istockphoto.com/id/1091901746/vector/watercolour-doodle-background.jpg?s=612x612&w=0&k=20&c=wlnNaWbzLd7vl36Y_dlSfKc9NFSOSFSID0DQV6APzL8=",
    name: "Portrait Painting",
    category: "portraits",
    type: "portrait",
    price: "700₹",
    description: "A portrait painting that beautifully captures the essence of a person.",
  },
  {
    id: 5,
    image: "https://media.istockphoto.com/id/1333638343/vector/abstract-blue-liquid-watercolor-background-with-golden-stains-cyan-marble-alcohol-ink.jpg?s=612x612&w=0&k=20&c=lsefqU-VNnONBbfxLe09E5Uf4wpPEObWTuTBuVgCvkM=",
    name: "Expressionist Artwork",
    category: "expressionism",
    type: "expressionist",
    price: "550₹",
    description: "An expressionist artwork that conveys intense emotions through vibrant strokes.",
  },
  {
    id: 6,
    image: "https://media.istockphoto.com/id/182179943/vector/colors-of-humanity-series.jpg?s=612x612&w=0&k=20&c=cnmI2yTaPOdXTbJejvhqUkc7KTAnb794oHXQHn4YZpk=",
    name: "Still Life Painting",
    category: "abstract art",
    type: "still life",
    price: "750₹",
    description: "A still life painting featuring carefully arranged objects with meticulous detail.",
  },
  {
    id: 7,
    image: "https://media.istockphoto.com/id/656634558/vector/rainbow-abstract-watercolor-background-hand-drawn-watercolor-stains-splashes-and-drops.jpg?s=612x612&w=0&k=20&c=9pNLnXi2sRPdidMMdvDTk8xCx2kQutGcH-OK48FWZug=",
    name: "Surrealistic Art",
    category: "expressionism",
    type: "surrealistic",
    price: "700₹",
    description: "A surrealistic art piece that explores dreamlike and fantastical elements.",
  },
  {
    id: 8,
    image: "https://media.istockphoto.com/id/1340935700/vector/tropical-luxury-exotic-seamless-pattern-pastel-colorful-banana-leaves-palm.jpg?s=612x612&w=0&k=20&c=tKjewa8sSig5a3XESHTNCyFSGZljSB7AmCMOX-Qo1bI=",
    name: "Cityscape Painting",
    category: "expressionism",
    type: "cityscape",
    price: "900₹",
    description: "A cityscape painting capturing the essence and energy of an urban environment.",
  },
  {
    id: 9,
    image: "https://media.istockphoto.com/id/1340935700/vector/tropical-luxury-exotic-seamless-pattern-pastel-colorful-banana-leaves-palm.jpg?s=612x612&w=0&k=20&c=tKjewa8sSig5a3XESHTNCyFSGZljSB7AmCMOX-Qo1bI=",
    name: "Geometric Abstraction",
    category: "expressionism",
    type: "geometric",
    price: "650₹",
    description: "A geometric abstraction showcasing precision and mathematical forms in art.",
  },
  {
    id: 10,
    image: "https://media.istockphoto.com/id/171159207/vector/plum-blossom.jpg?s=612x612&w=0&k=20&c=4MogLwUUiedsUo04ExyZ_hson9mvrpUG-FrajM0Z-P8=",
    name: "Abstract Portrait",
    category: "abstract portraits",
    type: "abstract",
    price: "850₹",
    description: "An abstract portrait that challenges traditional notions of portraiture.",
  },
  {
    id: 11,
    image: "https://media.istockphoto.com/id/1305757959/video/talented-couple-of-artists-draws-with-their-hands-on-the-canvas.jpg?s=640x640&k=20&c=CxldhIr1ua_1pU_UFqzXZcgNK6_sqf-1VJGcVm6pO9E=",
    name: "Impressionist Masterpiece",
    category: "expressionism",
    type: "impressionist",
    price: "750₹",
    description: "An impressionist masterpiece capturing the fleeting effects of light and color.",
  },
  {
    id: 12,
    image: "https://media.istockphoto.com/id/1399929817/vector/acrylic-painting-hand-drawn-oil-painting-abstract-art-background-brushstrokes-of-paint.jpg?s=612x612&w=0&k=20&c=2FxXu24MV7ZicuCCkKzy0Kt7pDo9jM8kYkyp5m6cyRE=",
    name: "Nature-inspired Art",
    category: "nature-inspired",
    type: "nature-inspired",
    price: "950₹",
    description: "Art inspired by nature, featuring flora and fauna in a harmonious composition.",
  },
 
];

export default Menu;
